### ISSUE TITLE
Does not build with setuptools>52.0.0

### ISSUE THREAD

**Issue by akmorrow13** [YosefLab/epitome#82]
Does not work with 56.2.0.

Some issue with `get_license()`, being parsed as a list instead of a string:
```
      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/setuptools/dist.py", line 172, in write_pkg_file
        license = rfc822_escape(self.get_license())
      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
        lines = header.split('\n')
    AttributeError: 'list' object has no attribute 'split'
```
