### PR TITLE
Python 3.9

### LINKED ISSUE #50: setup does not work with setuptools version 50.0.3
setuptools version 50.0.3 fails with error:

```
"command class %s must subclass Command" % cmd_class)
    distutils.errors.DistutilsClassError: command class <class 'setuptools.command.egg_info.egg_info'> must subclass Command
```
It works with setuptools version 51.3.3.post20210118.

### LINKED ISSUE #82: Does not build with setuptools>52.0.0
Does not work with 56.2.0.

Some issue with `get_license()`, being parsed as a list instead of a string:
```
      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/setuptools/dist.py", line 172, in write_pkg_file
        license = rfc822_escape(self.get_license())
      File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
        lines = header.split('\n')
    AttributeError: 'list' object has no attribute 'split'
```

### PR DESCRIPTION
**Pull request by btecu**
- Support `python 3.9`. Update dependencies.
- Fix `pytest` warning
- Ignore test data and reports

Closes #50.
Closes #82.

### CODE REVIEW

**Comment by akmorrow13** [comment]
Thank you @btecu, this is great! Long time no talk. Hope all is well!
